version: "3.4"
services:
  redis:
    container_name: redis
    image: redis

    command: redis-server --requirepass C0KHfa7sa9AmzNpWzcAu9eC67Reip7R5M

    ports:
      - 6379:6379
    networks:
      - backend

  backend_rest:
    container_name: backend
    build: .
    depends_on: [ redis ]
    ports:
      - 8080:8080
    volumes:
      - ./data:/usr/src/app/data
      - ./log:/usr/src/app/log
    networks:
      - backend

networks:
  backend:
    driver: bridge
